# Supabase Configuration

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
max_rows = 1000

[auth]
enabled = true
site_url = "exp://localhost:8081"
additional_redirect_urls = ["exp://localhost:8081"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
# Edge Functions configuration
enabled = true
